version: '3.9'

services:
  api-gateway:
    build:
      context: ./apiGateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - client
      - reservation 
      - salle
      - kafka
    networks:
      - my-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    networks:
      - my-network

  reservation:
    build:
      context: ./reservation
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    depends_on:
      - kafka
    networks:
      - my-network

  salle:
    build:
      context: ./salle
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    command:
      - "/bin/bash"
      - "-c"
      - "while ! nc -z zookeeper 2181; do sleep 1; done; /etc/confluent/docker/run"
    networks:
      - my-network

  kafka-consumer:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


